### ISSUE TITLE
After read README, still don't know how to run the test

### ISSUE THREAD

**Issue by hqhq** [huawei-openlab/oct#106]
As it claimed:

### Getting Started
- Read the [README](README.md) for build and test instructions

But I don't see any useful instructions about build and test. Can we improve this?

Thanks

**Comment by liangchenye** [comment]
Thank you for pointing it out.
I'm still working on it.
The first 'polished' version will be done by the end of this Friday.

**Comment by zenlinTechnofreak** [comment]
@hqhq @wangkirin @liangchenye @sunyuan3 
Hi, specstest have been renamed as specsValidator, its test scope is testing the compliance of runtime of runc with opencontainers/specs.
And the README.md of oct project is writing by @liangchenye now, anyone want to use specsValidator in time can read oct/tools/specsValidator/README.md.

Thanks.

**Comment by zenlinTechnofreak** [comment]
@hqhq @liangchenye ReadME.md now are better now, reference to,
https://github.com/huawei-openlab/oct/blob/master/README.md
https://github.com/huawei-openlab/oct/blob/master/tools/specsValidator/README.md
https://github.com/huawei-openlab/oct/blob/master/tools/bundleValidator/README.md

I think this issuse can be closed now.

**Comment by hqhq** [comment]
oct/README.md should be the only entry for users getting to know about OCT, and I think the most important information is `Getting Started` section, and that most important link [HowTo](https://github.com/huawei-openlab/oct/blob/master/tools/HowTO.md) in that section is still not available.

I think this issue can be closed once I can get that information from README.md.

**Comment by liangchenye** [comment]
Since 'oct' is the 'open container testing tools' now (the engine and case part is move to another project), each tool under 'oct' could be run independently. I changed the link of 'HowTo' to the link of 'specsValidator README.md' and 'bundle Validator README.md'.

**Comment by hqhq** [comment]
That works for me, thanks, closing it.
