### ISSUE TITLE
specstest-namespace.json

### ISSUE THREAD

**Issue by liangchenye** [huawei-openlab/oct#154]
Hi  @zenlinTechnofreak  
Which case is the result file 'namespace_out.json' for?

**Comment by wangkirin** [comment]
@liangchenye , hi , that json is belong to `oct/cases/specstest/namespace` , and I think we should have further discussion about how to name the folder of testcase in specstest

**Comment by liangchenye** [comment]
OK
I'll leave the issue open util we get a conclusion.

**Comment by zenlinTechnofreak** [comment]
@liangchenye @wangkirin  we should define the spec of the specstestcase name and output.
Anyway ,I think we can have a disscussion and give the suggestion to @liangchenye .

Later, I will show my suggestion here. And welecome your suggestion too @wangkirin .

**Comment by liangchenye** [comment]
OK, let's do that independently and share our ideas.

**Comment by zenlinTechnofreak** [comment]
@liangchenye @wangkirin @liugenping 
According analyzation of the LinuxSpecs structure from opencontainers/specs, items under spec maybe the same as it under linux. So my suggestion is as fllowers,
- Folder and file name definition:

``` sh
├── linux_namespace
├── linux_resources
│   ├── source
│   │   ├── a.go
│   │   └── xxx.go
│   └── Specstest-linux_resources-runc.json
├── linux_xxx
├── report
│   ├── linux_namespace.json
│   ├── linux_resources.json
│   ├── linux_xxx.json
│   ├── spec_root.json
│   ├── spec_version.json
│   └── spec_xxx.json
├── source
│   ├── configcovert
│   ├── hostsetup
│   ├── pkgxxx
│   └── specs
├── spec_root
│   ├── source
│   └── Specstest-spec_root-runc.json
├── spec_version
└── spec_xxx
```
- grain size of each testcase

Each grain size should test the item under Spec or Linux, not allowed to split the sub item into several cases.   

For example,
To test LinuxSpecs.Spec.Root, we should provide a testcase named spec_root, but not root_readonly_true and root_readonly_false.

Any other suggesion are welcomed.

**Comment by wangkirin** [comment]
@zenlinTechnofreak  you mean all situations of one spec item are tested in one case？

**Comment by liangchenye** [comment]
@wangkirin yes.
So far, the runtime test will be in one case.
The config test is not merged.
The bundle test is not defined (the OCI upstream have not reach a conclusion)

**Comment by zenlinTechnofreak** [comment]
Resolved, suggest to close it.

**Comment by zenlinTechnofreak** [comment]
Architecture and scope have been changed, so close it.
