### ISSUE TITLE
Disscustion for the format of the source code organization.

### ISSUE THREAD

**Issue by zenlinTechnofreak** [huawei-openlab/oct#16]
This issuse created to disscustion for the format of the source code organization.
such as, 
```
Cases/Benchmark/sysbench/cpu_load/Dockerfile/
```
or
```
Cases/benchmark/sysbench/cpu_load/source/
```
or
```
cases/benchmark/sysbench/cpu_load/source/
```

should be several parts, name format, organization format...etc

**Comment by ChengTiesheng** [comment]
Hi, @zenlinTechnofreak @liangchenye , I suggest that a new folder should be created for the source, such as test-tools. Test-tools and Cases are parallel. Then, there will be three folders: Cases, Test-Tools, Test-Engin.

**Comment by wangkirin** [comment]
i suggest we can org like this to put image files
`cases/benchmark/sysbench/cpu_load/source/dockerfile`  to put related docker images (dockerfile or *.tar.gz)
`cases/benchmark/sysbench/cpu_load/source/dockerfile`  to put related rkt images (*.aci and corresponding signature file )

**Comment by ChengTiesheng** [comment]
What about this?
cases/
test-tools/
test-engine/
--------------------------------------
In directory "cases", only test case and script can be added;
We can put iperf/cadvisor wrapper realization into test-tools directory.
Test-engine directory contains the realization of auto test framwork, which is owned by @liangchenye.

What is your opinions?

**Comment by zenlinTechnofreak** [comment]
@liangchenye  to your opinioin, the go source code(testcase) should be a functionality or a main func?

**Comment by zenlinTechnofreak** [comment]
@ChengTiesheng  so agree with u, where to store testtools such as cadvisor, should concerned now, can u make the decision with @liangchenye together?

**Comment by liangchenye** [comment]
The test-engine directory including
|___ schedular
|___ cpe (container_pool_engine)
|___ ts (test_server)
I'll do this part before 8.2, but will need others help later.

**Comment by zenlinTechnofreak** [comment]
@liangchengye what do u mean by "need others help later"?
is it means we have encrease human resource in this part in some future day?

**Comment by liangchenye** [comment]
About the test-tools, @ChengTiesheng and I discussed just now, I put the conclusion here first:
We can use this directory to store the Testing Tools.

But it is the short term plan.In the long term, we should have a repository (not on github, but maybe a simple http server).

[The problem we meet]
Tiesheng need to use iperf.
If there is no need to modify it, he can just simply use the following command in the dockerfile.
'apt install iperf'
But now Tiesheng need to change it.

The ideal way is:
He can first put that in another public repository or a third-party repository.
Second change the installation command in dockerfile like this:
'apt add repo 'http://some_thrid_part_repo"
'apt intall iperf'

**Comment by liangchenye** [comment]
There are three daemons, in the demo phase, I could finish that.
But once it became a real product, we need to think about the security issue, the different backend support issues and the etc. The workload will be heavy.

I will give a detailed report before 8.2.

**Comment by zenlinTechnofreak** [comment]
@liangchenye I got it, and will concern about it, plz let me know as quikly as u get changes in human request.thanks.

**Comment by zenlinTechnofreak** [comment]
@liangchenye @chengtiesheng OK, I think there are two case,
1 we have to do changes in source code in the testtool
2. we just use it.

To the first case, If necessary ,plz let @maquanyi know and disscussed with him.
To the cadvisor, I will try to use it directly, thus we do not need to store it in anywhere.

**Comment by wangkirin** [comment]
@liangchenye @ChengTiesheng  i still not clear where to put container image such as  `Dockerfile` and `aci` file of Rocket? put them in the `Case` folder ?

**Comment by ChengTiesheng** [comment]
Dockerfile is a must requirement for test cases, so I think it is appropriate to put Dockerfile into cases/xxx/source. @liangchenye @zenlinTechnofreak , what is your suggestions?

**Comment by zenlinTechnofreak** [comment]
@ChengTiesheng @ChengTiesheng @wangkirin quite agree with u to put it in cases/xx/source.
But the further question is there are two ways to realize this,
```
cases/benchmark/sysbench/cpu_load/source/dockerfile
cases/benchmark/sysbench/cpu_load/source/rktaci
```
or

```
cases/benchmark/sysbench/cpu_load_docker/source/dockerfile
cases/benchmark/sysbench/cpu_load_rkt/source/rktaci
```

**Comment by zenlinTechnofreak** [comment]
@liangchenye @ChengTiesheng @liugenping

A question is, when we provide go code testcase, what type of the function should be provided.
a library or a go rutine?
It is decided by the framework, if framework use g runtine to run testcase, the testcase should be go rutine(func main in source), Or,testcase only provide as library(not the main func in source code)

**Comment by liugenping** [comment]
I think should like go test frame, we can refer to it

**Comment by liangchenye** [comment]
@maquanyi  suggest we should use the lowercase and '-' as the dir name and file name.
For example, I should rename 
ocp-testing/engine/report/case01/Network-iperf.json 
to
ocp-testing/engine/report/case01/network-iperf.json

**Comment by zenlinTechnofreak** [comment]
@maquanyi @liangchenye 
I am so borther with the  capitalization of the first charactor of the dir name.
I think it is the working habit in windows os.
can we change it to the lowercase？

**Comment by liangchenye** [comment]
@zenlinTechnofreak yes, me too.
Rename them, except the README/HowTO/Makefile.

**Comment by liangchenye** [comment]
close, since we have a better solution: specstool
