### ISSUE TITLE
Specstest tools moved to oct/tools.

### ISSUE THREAD

**Issue by zenlinTechnofreak** [huawei-openlab/oct#186]
@wangkirin Specstest tools moved to oct/tools.It is going to merged this afternoon, plz refer to Init Specstest in new OCT, Add build script for tools(only enable build specstest tool) #184

**Comment by wangkirin** [comment]
@zenlinTechnofreak ，OK， I see these changes~~~~~

**Comment by wangkirin** [comment]
@zenlinTechnofreak Now we are going to work under the `master` branch??

**Comment by zenlinTechnofreak** [comment]
@wangkirin  Yes,welcome contributing to the oct/tools/specstest/

**Comment by wangkirin** [comment]
@zenlinTechnofreak OK，I think we'd better delete other useless branches

**Comment by zenlinTechnofreak** [comment]
@liangchenye The branch of specstesttool can be deleted now, we have totaly moved to master branch to oct .

**Comment by liangchenye** [comment]
Done!
