### ISSUE TITLE
Talking about next to do on specstest

### ISSUE THREAD

**Issue by zenlinTechnofreak** [huawei-openlab/oct#189]
### This issuse aims to talking about next todo on specstest tool ###
1. Enable specified output places in ./specs command line, such as "./specs -runc=xxx -specs=xxx -o=xxx.json".    done
2. Add item of specs version in testcases to avoid build err with the newest specs, enable framework to choose the testcases to run on specified specs, thus to avoid err caused by huage changing of specs, such as changing of adding runtime.json of specs.
3. Using configValidator in specstest tool to Validate config when using newest specs revesion.
4. Enable register func in framework.       done
5. Enable runc repo and set env path of root user on host machine in framework.     done
6. Rich the testcases to overall the opencontainers/specs.
7. Enable RKT test in specstest/adaptor.   
8. Enable the freamework of specstest supporting the guest programme running in containers.        

@liangchenye @maquanyi @wangkirin

**Comment by zenlinTechnofreak** [comment]
@liangchenye @wangkirin 
4. Enable register func in framework.
This to do have been down, people who want to add testcase , do not need to new and run testsuite in specs.go, just need to import the testcase pkg in spec.go.
 For example, in case specroot,
in cases/specroot/root.go
``` go
func init() {
	TestSuiteRoot.AddTestCase("TestReadOnlyTrue", TestReadOnlyTrue)
	TestSuiteRoot.AddTestCase("TestReadOnlyFalse", TestReadOnlyFalse)
	TestSuiteRoot.AddTestCase("TestPathError", TestPathError)
	manager.Manager.AddTestSuite(TestSuiteRoot) // adding testsuite here.
}
```
in specs.go
``` go
import (
	"flag"
	"fmt"
	// _ "github.com/huawei-openlab/oct/tools/specstest/cases/linuxcapabilities"
	_ "github.com/huawei-openlab/oct/tools/specstest/cases/linuxnamespace"
	// _ "github.com/huawei-openlab/oct/tools/specstest/cases/linuxresources"
	// _ "github.com/huawei-openlab/oct/tools/specstest/cases/linuxrlimits"
	// _ "github.com/huawei-openlab/oct/tools/specstest/cases/linuxselinuxlabel"
	// _ "github.com/huawei-openlab/oct/tools/specstest/cases/linuxsysctl"
	_ "github.com/huawei-openlab/oct/tools/specstest/cases/specmount"
	_ "github.com/huawei-openlab/oct/tools/specstest/cases/specplatform"
	_ "github.com/huawei-openlab/oct/tools/specstest/cases/specroot" // import specroot pkg here
	_ "github.com/huawei-openlab/oct/tools/specstest/cases/specversion"
	"github.com/huawei-openlab/oct/tools/specstest/hostenv"
	"github.com/huawei-openlab/oct/tools/specstest/manager"
	"github.com/huawei-openlab/oct/tools/specstest/utils"
	"log"
)
```

Do not need any more changes.

**Comment by zenlinTechnofreak** [comment]
@liangchenye @wangkirin 
1. Enable specified output places in ./specs command line, such as "./specs -runc=xxx -specs=xxx -o=xxx.json".
This to do have been down ,
U can use ./specs -o to specify the output place, reuslt file name is linuxspec.jsn. If anyone donot use "-o", the default output place is "oct/tools/specstest/report".

**Comment by zenlinTechnofreak** [comment]
@liangchenye @wangkirin 
5. Enable runc repo and set env path of root user on host machine in framework.
This to do have been done, specstesttool can automatical checking runc repo and its env.

**Comment by zenlinTechnofreak** [comment]
So far as now, the status of next to do in this issues are as below,
who have been done,
1. Enable specified output places in ./specs command line, such as "./specs -runc=xxx -specs=xxx -o=xxx.json".    done
2. Add item of specs version in testcases to avoid build err with the newest specs, enable framework to choose the testcases to run on specified specs, thus to avoid err caused by huage changing of specs, such as changing of adding runtime.json of specs.
4. Enable register func in framework.       done
5. Enable runc repo and set env path of root user on host machine in framework.     done
6. Rich the testcases to overall the opencontainers/specs. done at 80%
8. Enable the freamework of specstest supporting the guest programme running in containers.  done 

I think Others should be pending, and it is the time for us going to start adjusting the specsValidator  to the specs on v0.1.1, because runc can support the specs on v0.1.1 now.

@wangkirin @maquanyi @liangchenye

**Comment by liangchenye** [comment]
Agree and congratulations.

**Comment by zenlinTechnofreak** [comment]
Closed this issuse and create a new one for new task list,
Talking about next to do list from Auth 29th on specsValidator #273
