### ISSUE TITLE
Delete the oct/cases folder for avoiding missunderstanding of new oct?

### ISSUE THREAD

**Issue by zenlinTechnofreak** [huawei-openlab/oct#200]
@liangchenye Shall we delete the oct/cases folder?
Today, some have attemped to use oct, but existing of oct/cases consult him.
Thanks.

**Comment by liangchenye** [comment]
I just moved two tools to oct-engine.

 I'll delete the cases folder in oct in 10 minutes.
( but left it in oct-engine)

**Comment by liangchenye** [comment]
done. close
