### ISSUE TITLE
Bug find while running runtimeValidator

### ISSUE THREAD

**Issue by initlove** [huawei-openlab/oct#278]
./runtimeValidator -rtags=apparmor
Testing Revision:
   Specs revision: newest commit
   Runc revision: newest commit
Going to update revision, maybe need several mins, plz be patient!
Testing output:
   ./report/linuxspec.json
Starting to create boundle...
        Going to create bind path for hostend-containerend communicating...
        done
        Creating root filesystem for boundle, maybe need several mins...
Create boundle done
TestReadOnlyTrue                                                    failed
TestReadOnlyFalse                                                   failed
TestPathError                                                    unknowErr
panic: runtime error: index out of range

goroutine 1 [running]:
runtime.panic(0x4ffdc0, 0x6990f7)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/huawei-openlab/oct/tools/runtimeValidator/cases/specprocess.checkOutUser(0xc210068480, 0xbd, 0x51d360, 0x5, 0x5232a0, ...)
        /Go/src/github.com/huawei-openlab/oct/tools/runtimeValidator/cases/specprocess/process_v0.1.1.go:189 +0x750
github.com/huawei-openlab/oct/tools/runtimeValidator/cases/specprocess.testProcessUser(0xc21005c3c0, 0xc210079140, 0x1, 0x0, 0x0, ...)
        /Go/src/github.com/huawei-openlab/oct/tools/runtimeValidator/cases/specprocess/process_v0.1.1.go:67 +0x426
github.com/huawei-openlab/oct/tools/runtimeValidator/cases/specprocess.TestBase(0x0, 0x0)
        /Go/src/github.com/huawei-openlab/oct/tools/runtimeValidator/cases/specprocess/test_process_v0.1.1.go:25 +0x1b8
reflect.Value.call(0x4d9280, 0x563230, 0x130, 0x51dc20, 0x4, ...)
        /usr/lib/go/src/pkg/reflect/value.go:474 +0xe0b
reflect.Value.Call(0x4d9280, 0x563230, 0x130, 0x0, 0x0, ...)
        /usr/lib/go/src/pkg/reflect/value.go:345 +0x9d
github.com/huawei-openlab/oct/tools/runtimeValidator/manager.(*TestSuite).Run(0xc210050080)
        /Go/src/github.com/huawei-openlab/oct/tools/runtimeValidator/manager/casemanager.go:117 +0xa1
main.main()
        /Go/src/github.com/huawei-openlab/oct/tools/runtimeValidator/specs_v0.1.1.go:124 +0x75b

goroutine 4 [finalizer wait]:
runtime.park(0x40a960, 0x69c110, 0x69a7c8)
        /usr/lib/go/src/pkg/runtime/proc.c:1342 +0x66
runfinq()
        /usr/lib/go/src/pkg/runtime/mgc0.c:2279 +0x84
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1394

**Comment by liangchenye** [comment]
@zenlinTechnofreak @wangkirin 
Two questions:
1. both of these failed, is that just v0.1.1 bug?
TestReadOnlyTrue failed
TestReadOnlyFalse failed
2. it crashes.

**Comment by zenlinTechnofreak** [comment]
@liangchenye 
I have created a PR to support the specs.Version == 0.2.0,
Now, U can have a try to find out weather the bug have fixed.
thx.
