### ISSUE TITLE
Test cases discuss

### ISSUE THREAD

**Issue by liangchenye** [huawei-openlab/oct#329]
The current test suite is quite good, the following suggestion may not be necessary, but let's discuss here.

1).  Add an extra 'description' session to the cases.conf ?    
  for example, can we add 'check rootfs is false' to describe one of the process case?
  So in the testing output part, it is easier for user to see what has been tested?
2).  Add a '--error-only' parameter to the main function, so the user just need to know what is wrong.
3) Adda conclusion output?
     for example. '190 out of 200 tests were passed.'

**Comment by zenlinTechnofreak** [comment]
LGTM.
The main func in supporting rkt is not ready yet, task in next step is going to modify the output to be better.

**Comment by liangchenye** [comment]
@zenlinTechnofreak  @wangkirin   One step is add a 'testunit' to wrap the previous validate.go

**Comment by wangkirin** [comment]
@liangchenye , Yes, 1) is really what we should considered , now we use `case.conf ` for the convenience of editing cases and using `generator` ,  we can come up with a solution to balance simplicity and understandability. 2) and 3) is easy to do

**Comment by wangkirin** [comment]
@liangchenye @zenlinTechnofreak  current definition of test case is seting in `case.conf` is  `Name=Args..` , we can change to `Name:[Description]=Args`

**Comment by zenlinTechnofreak** [comment]
@wangkirin yes, but how to descript the cases correctly should be a difficult thing. I think we can First modify the output to be more clealy.

**Comment by zenlinTechnofreak** [comment]
@wangkirin @liangchenye 
I have fixed the bug of the testunit  and modify the design of testUnit using Object-oriented programming.
Next step, we will easily to make the output clearly.

**Comment by zenlinTechnofreak** [comment]
@liangchenye oct now have format ouput and support to choise ouput format,
```
ocitest -o all  
```
or
```
 ocitest -o err-only
```
