### ISSUE TITLE
Not enough memory bug caused by oci2aci tool

### ISSUE THREAD

**Issue by zenlinTechnofreak** [huawei-openlab/oct#351]
If running oct for rkt testing frequently, bug for not enough memory for testing will occour, that is caused by the bug from oci2aci, relatived issuse as below,
aci images in /tmp dir is not necessary [#6](https://github.com/huawei-openlab/oci2aci/issues/6)

**Comment by ChengTiesheng** [comment]
Hi @zenlinTechnofreak, the bug has been solved, please update oci2aci tool and enjoy it:-)

**Comment by zenlinTechnofreak** [comment]
@ChengTiesheng  congratulations, It is fixed. Thanks very much.
