### ISSUE TITLE
Milestones discussion

### ISSUE THREAD

**Issue by zenlinTechnofreak** [huawei-openlab/oct#6]
Hi @maquanyi @mengfanliang @liangchenye @ChengTiesheng @huawei-openlab/owners 

I have wrote the milestone draft for the project ,we can disscuss it in this issuse.
List my draft  below,

```
0.10.0
 Due by August 2, 2015   Last updated 20 minutes ago
OCP-Testing draft, suportted docker only.
Test Architecture:
finish native architecture coding, conclude request of test server & container pool
Runtime test:
finish benchmark testcase, supportted docker only
Network test:
finish network architechture coding, supportted docker only
Regitry protocol:
finish designe & interface for docker V1&V2 regitry protocol, supporting test architecture
```

```
0.20.0
 Due by August 16, 2015   Last updated 4 minutes ago
OCP-Testing draft, suportted docker only, runnable version
Test Architecture:
intergrate testcases
Runtime test:
finish docker specs testcase, supportted docker only
Network test:
finish network perfomance testcases coding, supportted docker only
Regitry protocol:
finish coding for docker V1&V2 regitry protocol, supporting test architecture
```

```
1.00
 Due by August 30, 2015   Last updated 2 minutes ago
V1 realease version, support docker & rkt container.
```

**Comment by liangchenye** [comment]
Cool, my work on the architecture including these:
1 the scheduler 
1.1 parse the test case (check its validation first)
1.2 calling different services (test server, container pool)
      in the first round (before 8.2), I'll use the demo test server and container pool
2 test server daemon
2.1   return the resource id to the scheduler (before 8.2)
2.2   deploy the test case (before 8.16)
3 container pool daemon
3.1 return the image availability and the id/name to the scheduler (before 8.2)
3.2 implement the 'docker' back-end (before 8.16)

**Comment by wangkirin** [comment]
i wonder if we should define a standard about how to orgnized the filesystem. For example，how to name the file and the folder, and the hierarchy relationship of files

**Comment by zenlinTechnofreak** [comment]
@wangkirin I have new a issuse fo disscution for this task, the  format of the source organization for the project, u can give your suggestion in the issuse.
Disscustion for the format of the source code organization. #16

**Comment by zenlinTechnofreak** [comment]
@liangchenye @mengfanliang @maquanyi @wangkirin @ChengTiesheng 
noftification:
     the meeting today afternoon is delayed to tomorrow after 16:00, email notification will send out to you tormorrow afternoon, plz reserve your time.

**Comment by wangkirin** [comment]
In milestone 0.1,  how many kinds of container should we support ? Docker V1&V2? Rkt?Kurma?Jetpack?

**Comment by ChengTiesheng** [comment]
I think docker will be supported first. With the full experience of docker testing, we can support other containers step by step.

**Comment by zenlinTechnofreak** [comment]
plz @liangchenye @wangkirin @ChengTiesheng @liugenping update your job status for Milestone 0.10.0.
sereral parts content,
1. what have been finished this week.
2. what is the next plan for next week.

@maquanyi @mengfanliang @haijunTan

**Comment by wangkirin** [comment]
I finish the part of sysbench under the enviroment of Docker and Rkt
Next week will finish the Kurma part and the Jetpack part

**Comment by zenlinTechnofreak** [comment]
@liangchenye @liugenping @maquanyi @wangkirin @ChengTiesheng @haijunTan
I have update the milestone.
```
0.10
 Due by August 2, 2015   Last updated less than a minute ago
OCP-Testing draft, suportted docker and rkt only.
A:Test Architecture:
1 the scheduler
1.1 parse the test case (check its validation first)
1.2 calling different services (test server, container pool)
in the first round (before 8.2), I'll use the demo test server and container pool
2 test server daemon
2.1 return the resource id to the scheduler (before 8.2)
3 container pool daemon
3.1 return the image availability and the id/name to the scheduler (before 8.2)

B. Benchmark test:
finish benchmark testcase, supportted docker and RKT
1. Develop cadvisor docker test client, provide testcase;
2. Develop in cadvisor to support RKT, and provide RKT test client.
3. Develop sysbench testcase.

C.Network test:
finish network architechture coding, supportted docker only
```
```
0.20
 Due by August 16, 2015   Last updated about 1 hour ago
OCP-Testing draft, suportted docker only, runnable version
Test Architecture:
intergrate testcases
Runtime test:
finish docker specs testcase, supportted docker only
Network test:
finish network perfomance testcases coding, supportted docker only
Regitry protocol:
finish coding for docker V1&V2 regitry protocol, supporting test architecture
```

##We can have further talk with it after @maquanyi came back.

**Comment by liangchenye** [comment]
Update:
working on another micro service : TestDB.
The current designation is:
1) it clone Cases from our github (per hour for example)
2) check if there were any updated case or new case
3) send case test request 'scheduler' (in this case, make scheduler real scheduler)
4) once 'scheduler' finish the work, send the testing result back to TestDB
5) TestDB will put the result to the related Case dir, and use 'report' to generate the report with markdown format
6) TestDB will push the testing result & markdown report to github.

**Comment by zenlinTechnofreak** [comment]
Architecture and scope have been changed, so close it.
