### ISSUE TITLE
OCP is now OCI

### ISSUE THREAD

**Issue by vbatts** [huawei-openlab/oct#66]
There was a renaming from "Project" to "Initiative".

**Comment by ChengTiesheng** [comment]
Thanks for your reminder, we will update it soon:)

**Comment by liangchenye** [comment]
:)  We were thinking about choosing a cool name @vbatts , but struggling...

**Comment by liangchenye** [comment]
hi @vbatts, the project changed to oct (open container testing) now

**Comment by vbatts** [comment]
:-D :octopus: 
Thanks y'all
