### ISSUE TITLE
How to do bundle compatibility test?

### ISSUE THREAD

**Issue by zenlinTechnofreak** [huawei-openlab/oct#78]
This issuse opened for disscussion for test of bundle.
I have read the [bundle.md](https://github.com/opencontainers/specs/blob/master/bundle.md), and try to find out how to test the bundle spec.
So far, my consider is, bundle test should be contain 2 parts:
- Use config.json and rootfs, container can be run normall;
- The whole container bundle(conclude config.json and rootfs) can be moved to another machine and run well;
- Some test about signature(no config for it in [specs](https://github.com/opencontainers/specs) yet).

**Comment by liangchenye** [comment]
The OCI community is talking about add a metafile to describe the files in the containers.
They don't reach a conclusion yet.
But it will be something like:
[ {"name": "/usr/bin/test", "uid": 1, "gid": 1, "mod": 644},
  {"name": "/usr/lib/testlib.so", "uid": 1, "gid": 1, "mode": 644},
]
so the bundle test will be:
check if the files listed in the bundle were real exist.
check if the files have the same attributes with defined in the metadata.

**Comment by zenlinTechnofreak** [comment]
resolved.
